config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index" #views/prototypes/index.html.erbを呼び出す
  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do #prototypesコントローラーにアクションを定義
    resources :comments, onry: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  #userモデルと１対１で関連づける
  belongs_to :prototype
  #prototypeモデルと１対１で関連づける

  validates :content, presence: true
  #入力された値を検証,空ではないか
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user                        #userモデルと１対１で関連づける
  has_one_attached :image                 #Active Storage設定１つのファイルを追加する
  has_many :comments, dependent: :destroy #prototypeモデルが削除された場合commentsモデルも削除

  validates :title,      presence: true #入力された値を検証,空でないか
  validates :catch_copy, presence: true #入力された値を検証,空でないか
  validates :concept,    presence: true #入力された値を検証,空でないか
  validates :image,      presence: true #入力された値を検証,空でないか
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,       presence: true #入力された値を検証,空でないか
  validates :profile,    presence: true #入力された値を検証,空でないか
  validates :occupation, presence: true #入力された値を検証,空でないか
  validates :position,   presence: true #入力された値を検証,空でないか

  has_many :prototypes #prototypeモデルに１対多で関連づける
  has_many :comments  #commentモデルに１対多で関連づける
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  #deviseに属する画面に遷移したとき[configure_permitted_parameters]メソッドを呼び出す。

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :position, :occupation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype)
    else
      @prototype = @comment.prototype
      @comments = @prototype.comments
      render "prototypes/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :prototype_find, except: [:index, :new, :create]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :redirect_root, only: [:edit, :update, :destroy]

  def index #indexアクションを設定
    @prototypes = Prototype.all
    #PrototypeクラスにPrototypeモデル全ての情報を@prototypesに代入
  end

  def new #newアクションを設定
    @prototype = Prototype.new
    #Prototypeクラスの空のインスタンスを作成し,@prototypesへ代入
  end

  def create #createアクションを設定
    @prototype = Prototype.new(prototype_params)
    #prototypep_paramsで取得したデータを,@prototypesへ代入
    if @prototype.save
    #保存ができた場合以下の処理を実行
      redirect_to root_path
      #index.html.erbへ遷移
   else#保存ができなかった場合以下の処理を実行
      render :new
      #new.html.erbへ遷移
    end
  end

  def show #showアクションを設定
    @comment = Comment.new
    #Commentクラスの空のインスタンスを作成し,@commentへ代入
    @comments = @prototype.comments
    #@protptypeと関係を持つcommentsを取得し@commentsへ代入
  end

  def edit #editアクションを設定
    @prototype = Prototype.find(params[:id])
  end

  def update #updateアクションを設定
    if @prototype.update(prototype_params)
      #prototype_paramsで取得したデータで更新できた場合以下の処理を実行
      redirect_to prototype_path(@prototype)
      #show.html.erbへ遷移
    else
      render :edit
      #edit.html.erbへ遷移
    end
  end

  def destroy #destroyアクションを設定
    if @prototype.destroy
      #@prototypeのデータを削除できた場合以下の処理を実行
      redirect_to root_path
      #index.html.erbに遷移
    else
      redirect_to root_path
      #index.html.erbに遷移
    end
  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
    #prototypeモデルの[title,catch_copy,concept,image]とuser_idのログイン中のユーザーidを取得する
  end

  def redirect_root
    redirect_to root_path unless current_user == @prototype.user
  end

  def prototype_find
    @prototype = Prototype.find(params[:id])
    #取得したidをもつprototypeのレコードを取得し@prototypeに代入
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
          <%# ログインしている場合以下の処理を実行 %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%# destroyアクションへデータを送る%>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
              <%# new.html.erbへ遷移 %>
            </div>
              <%# // ログインしているときは上記を表示するようにしましょう %>
              <%# ログインしていないときは以下を表示するようにしましょう %>
          <% else %>
          <%# ログインしていない場合以下の処理を実行 %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%# views/session/new.html.erbへ遷移 %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              <%# views/registration/new.html.erbへ遷移 %>
            </div>
              <%# // ログインしていないときは上記を表示するようにしましょう %>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype) %>
  <%# prototypeモデルのimageを呼び出す %>
  <div class="card__body">
    <%= link_to prototype.title, prototype_path(prototype), class: :card__title %>
    <%#prototypeモデルのtitleを呼び出す %>
    <p class="card__summary">
      <%= prototype.catch_copy %>
      <%# prototypeモデルのcatchを呼び出す %>
    </p>
    <%= link_to "by #{prototype.user.name}", user_path(prototype.user), class: :card__user %>
    <%# prototypeモデルに関連するuserモデルのnameを呼び出す%>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? #ユーザーがログインしている場合trueを返す %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
        <%# ログインしているユーザー名を表示 %>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示 %>
    <div class="card__wrapper">
      <%= render partial: 'prototype', collection: @prototypes %>
      <%# _prototype.html.erbを部分テンプレートとして呼び出し,@prototype内の要素の数だけ部分テンプレートを繰り返し表示 %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render partial: "form", locals: { prototype: @prototype }%>
        <%# _form.html.erbを部分テンプレートで呼び出し,パーシャル内のprototypeに@prototypeを格納する %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if current_user == @prototype.user %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
        <%# インスタンス@prototypeのimageを呼び出す %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
            <%# インスタンス@prototypeのcatch_copyを呼び出す %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
            <%# インスタンス@prototypeのconceptを呼び出す %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
        <%# ログインしている場合以下の処理を実行する %>
          <%= form_with model: [@prototype, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content%>
              <%= link_to "（#{comment.user.name}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'prototypes/prototype', collection: @user.prototypes %>
      </div>
    </div>
  </div>
</div>